# frozen_string_literal: true

require_relative "sequel_ace_release/error"
require_relative "sequel_ace_release/config"
require_relative "sequel_ace_release/canonical_json"
require_relative "sequel_ace_release/command_runner"
require_relative "sequel_ace_release/git_repository"
require_relative "sequel_ace_release/release_naming"
require_relative "sequel_ace_release/release_publisher"
require_relative "sequel_ace_release/deployment_guard"
require_relative "sequel_ace_release/approval"
require_relative "sequel_ace_release/manifest"
require_relative "sequel_ace_release/build_reconciler"
require_relative "sequel_ace_release/notes"
require_relative "sequel_ace_release/version_files"
require_relative "sequel_ace_release/http_transport"
require_relative "sequel_ace_release/github_client"
require_relative "sequel_ace_release/app_store_connect_client"
require_relative "sequel_ace_release/cloud_run_status"
require_relative "sequel_ace_release/metadata_validator"
require_relative "sequel_ace_release/submission_reconciler"
require_relative "sequel_ace_release/failure_recorder"
require_relative "sequel_ace_release/publish_handoff"
require_relative "sequel_ace_release/forward_build_recovery"
require_relative "sequel_ace_release/tar_archive_validator"
require_relative "sequel_ace_release/artifact_verifier"
require_relative "sequel_ace_release/planner"
require_relative "sequel_ace_release/cli"

module SequelAceRelease
  VERSION = "1.0.0"
end
