//
//  SAConnectionFormHelpers.swift
//  Sequel Ace
//
//  Three small pure helpers lifted out of SPConnectionController:
//    - newFavoriteID()       — generates the integer ID stored in
//                              SPFavoriteIDKey for a fresh favorite.
//    - stripInvalidCharacters(_:) — used everywhere a user-entered
//                              string flows into a favorite (the
//                              connection screen disallows newlines
//                              and surrounding whitespace).
//    - generateName(...)     — auto-name for a connection when the
//                              user hasn't typed one; falls back to
//                              host[/database] or "localhost".
//
//  Pure Swift, no AppKit / ObjC dependencies. Compiled into both the
//  app and Unit Tests targets (same pattern as SAViewMode /
//  SAConnectionDetailsValidator).
//

import Foundation

@objc final class SAConnectionFormHelpers: NSObject {

    /// Generate the integer ID stored under `SPFavoriteIDKey` for a
    /// new favorite. Matches the original C expression:
    ///
    ///     [NSNumber numberWithInteger:[[NSString stringWithFormat:@"%f",
    ///        [[NSDate date] timeIntervalSince1970]] hash]];
    ///
    /// i.e. hash of the time-interval-since-1970 stringified as `%f`.
    /// The IDs are stored in the favorites plist on disk; the
    /// "stringify-then-hash" shape MUST be preserved for new IDs to
    /// keep their distribution and not collide with the existing
    /// favorites store on upgrade.
    @objc static func newFavoriteID() -> NSNumber {
        let timestamp = String(format: "%f", Date().timeIntervalSince1970)
        return NSNumber(value: (timestamp as NSString).hash)
    }

    /// Trim leading/trailing whitespace + newlines, then strip out
    /// any remaining embedded newlines. The connection screen blocks
    /// these characters from reaching the favorites plist (they'd
    /// break copy/paste and the autogenerated name format).
    @objc static func stripInvalidCharacters(_ subject: String) -> String {
        let trimmed = subject.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.replacingOccurrences(of: "\n", with: "")
    }

    /// Auto-generate a connection name from the form fields. Returns
    /// `nil` when the form doesn't have enough to name a connection
    /// — the controller falls back to keeping whatever the user
    /// already typed.
    ///
    /// Rules (preserved from `-_generateNameForConnection`):
    ///   - Socket connections always name themselves "localhost"
    ///     (the host field is irrelevant for them).
    ///   - All other connection types require a non-empty host or
    ///     they return nil.
    ///   - When a database is set, append `/<database>`.
    ///
    /// Empty database treated as "no database" (the original used
    /// `[[self database] length]`, so this matches).
    @objc static func generateName(
        type: SAConnectionType,
        host: String,
        database: String
    ) -> String? {
        if type != .socket, host.isEmpty {
            return nil
        }
        let base = (type == .socket) ? "localhost" : host
        if database.isEmpty {
            return base
        }
        return "\(base)/\(database)"
    }
}
