//
//  SAVaultRoleListController.swift
//  Sequel Ace
//
//  Owns the behaviour behind the Vault "Role" combo box: fetching the role list
//  from Vault (off the main thread, via OIDC when needed), fuzzy-ordering it,
//  populating/reordering the dropdown, debouncing, invalidating on context
//  changes, and discarding stale/aborted responses. SPConnectionController keeps
//  only the bindings, outlets and thin IBAction/delegate forwarders.
//

import AppKit

/// Controller-side context and callbacks the role-list controller needs.
/// Implemented by SPConnectionController.
@objc protocol SAVaultRoleListControllerDelegate: AnyObject {
    func vaultRoleListCurrentHost() -> String
    func vaultRoleListCurrentPort() -> String
    func vaultRoleListCurrentOIDCMount() -> String
    func vaultRoleListCurrentMount() -> String
    func vaultRoleListCurrentRole() -> String
    /// A connect/test is in flight — refreshing would start a clashing OIDC login.
    func vaultRoleListShouldDeferForActiveConnection() -> Bool
    /// The window is closing (its document is gone) — drop any response.
    func vaultRoleListWasTornDown() -> Bool
    /// A real role was picked from the dropdown: mark edited + regenerate the
    /// autogenerated favorite name.
    func vaultRoleListDidCommitSelection()
    /// Enable/disable Connect and Test while a refresh (possible OIDC login) runs.
    func vaultRoleListSetConnectControlsEnabled(_ enabled: Bool)
}

@objc final class SAVaultRoleListController: NSObject {

    @objc weak var delegate: SAVaultRoleListControllerDelegate?

    private weak var comboBox: NSComboBox?
    private weak var refreshButton: NSButton?
    private weak var progressIndicator: NSProgressIndicator?

    /// Roles fetched for the current Vault context. Cleared whenever the context
    /// changes so the dropdown can't offer a role from a different server/mount.
    private var availableRoles: [String] = []

    /// Debounce token for reorder-while-typing.
    private var reloadToken: Int = 0

    /// Identifier of this window's in-flight refresh OIDC login (if any), so a
    /// close/cancel can abort exactly this login and free the callback port.
    private var activeLoginIdentifier: String?

    /// True from the moment a refresh starts its background LIST until the response
    /// is handled. A refresh may hold the fixed OIDC callback port, so every
    /// connection start (not just the Connect/Test buttons) must refuse to run
    /// while this is set — see -[SPConnectionController initiateConnection:].
    private var isRefreshing = false

    /// Whether a role refresh is currently in flight. Connection entry points check
    /// this to avoid launching an OIDC login that clashes on the callback port.
    @objc func isRefreshInFlight() -> Bool { return isRefreshing }

    @objc(initWithComboBox:refreshButton:progressIndicator:)
    init(comboBox: NSComboBox, refreshButton: NSButton, progressIndicator: NSProgressIndicator) {
        self.comboBox = comboBox
        self.refreshButton = refreshButton
        self.progressIndicator = progressIndicator
        super.init()
    }

    // MARK: - Dropdown population

    /// Rebuild the dropdown from the fetched list + the currently typed query.
    @objc func reloadItems() {
        guard let comboBox = comboBox else { return }
        // While editing, the committed -stringValue can lag the field editor.
        let query = comboBox.currentEditor()?.string ?? comboBox.stringValue
        let ordered = SAVaultRoleFilter.orderedRoles(availableRoles, query: query)
        comboBox.removeAllItems()
        comboBox.addItems(withObjectValues: ordered)
    }

    /// Debounce the reorder so rapid typing doesn't reshuffle the popup on every
    /// keystroke. A GCD timer fires in all run-loop modes (unlike
    /// -performSelector:afterDelay:, which is starved during event tracking).
    @objc func scheduleDebouncedReload() {
        reloadToken += 1
        let token = reloadToken
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.15) { [weak self] in
            guard let self = self, self.reloadToken == token else { return }
            self.reloadItems()
        }
    }

    /// Drop the fetched role list (tied to a specific server/token/mount) and
    /// clear the dropdown. Call whenever any Vault context field changes.
    ///
    /// Also abort any in-flight refresh login: it is bound to the now-stale
    /// host/port/OIDC mount and may be parked in the OIDC browser flow for the
    /// old server. Cancelling makes the background LIST return promptly so the
    /// completion handler re-enables Connect/Test instead of leaving them
    /// disabled until the stale login times out; the result is discarded there
    /// as stale.
    @objc func invalidateRoles() {
        cancelActiveLogin()
        availableRoles = []
        reloadItems()
    }

    /// Handle a dropdown selection: ignore the non-selectable separator row,
    /// otherwise notify the delegate that a role was committed.
    @objc func handleComboSelectionChange() {
        guard let comboBox = comboBox else { return }
        let idx = comboBox.indexOfSelectedItem
        if idx >= 0, let value = comboBox.itemObjectValue(at: idx) as? String, value == SAVaultRoleFilter.separator {
            // The separator isn't a real role; restore the field to the current value.
            DispatchQueue.main.async { [weak self] in
                comboBox.stringValue = self?.delegate?.vaultRoleListCurrentRole() ?? ""
            }
            return
        }
        delegate?.vaultRoleListDidCommitSelection()
    }

    // MARK: - OIDC login lifecycle

    /// Ask the user before an OIDC browser login opens. Called from the background
    /// LIST thread the instant a browser popup becomes imminent — whether because
    /// no token is cached or because a cached token turned out to be expired — so
    /// the prompt covers every path that can open the browser, not just the
    /// no-token case. Runs synchronously on the main thread and returns the choice.
    private func confirmBrowserLoginOnMainThread() -> Bool {
        if Thread.isMainThread { return runBrowserLoginConfirm() }
        return DispatchQueue.main.sync { self.runBrowserLoginConfirm() }
    }

    private func runBrowserLoginConfirm() -> Bool {
        let confirm = NSAlert()
        confirm.messageText = NSLocalizedString("Sign in to Vault?", comment: "Vault roles refresh – login confirm")
        confirm.informativeText = NSLocalizedString("Listing roles requires authenticating to Vault, which will open your web browser.", comment: "Vault roles refresh – login confirm detail")
        confirm.addButton(withTitle: NSLocalizedString("Continue", comment: "continue button"))
        confirm.addButton(withTitle: NSLocalizedString("Cancel", comment: "cancel button"))
        return confirm.runModal() == .alertFirstButtonReturn
    }

    /// Abort this window's in-flight refresh OIDC login (on window close/cancel)
    /// so its listener releases the fixed localhost callback port.
    @objc func cancelActiveLogin() {
        if let identifier = activeLoginIdentifier, !identifier.isEmpty {
            VaultOIDCHandler.cancelActiveLogin(identifier: identifier)
        }
    }

    // MARK: - Refresh

    @objc func refresh() {
        guard let delegate = delegate else { return }

        // Don't refresh during a connect/test: it would start a second OIDC login
        // clashing on the fixed callback port, and Connect is repurposed as Cancel.
        if delegate.vaultRoleListShouldDeferForActiveConnection() { return }

        let mount = delegate.vaultRoleListCurrentMount()
        if mount.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            NSAlert.createWarningAlert(title: NSLocalizedString("Enter a Vault mount first", comment: "Vault roles refresh – missing mount"),
                                       message: NSLocalizedString("The list of roles is read from <mount>/roles. Fill in the Vault mount field, then refresh.", comment: "Vault roles refresh – missing mount detail"))
            return
        }

        let host = delegate.vaultRoleListCurrentHost()
        let port = delegate.vaultRoleListCurrentPort()
        let oidcMount = delegate.vaultRoleListCurrentOIDCMount()

        // The browser-login confirmation is decided in the background flow, right
        // before a login would actually open the browser (see confirmBrowserLogin
        // passed to listRoles). That covers every case that can open the browser —
        // no cached token *and* a cached-but-expired token — instead of an upfront
        // presence-only check that a stale token would slip past.

        // Scope the login to this refresh so a close/cancel aborts only this one.
        let loginIdentifier = VaultOIDCHandler.prepareActiveLogin()
        activeLoginIdentifier = loginIdentifier

        refreshButton?.isEnabled = false
        // A refresh may open the same OIDC login as connecting (fixed callback
        // port), so block Connect/Test until it finishes.
        delegate.vaultRoleListSetConnectControlsEnabled(false)
        progressIndicator?.isHidden = false
        progressIndicator?.startAnimation(self)
        isRefreshing = true

        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            var error: NSError?
            let roles = VaultAuthManager.listRoles(host: host, port: port, oidcMount: oidcMount,
                                                   mount: mount, loginIdentifier: loginIdentifier,
                                                   confirmBrowserLogin: { [weak self] in
                                                       self?.confirmBrowserLoginOnMainThread() ?? false
                                                   },
                                                   error: &error)
            VaultOIDCHandler.clearPreparedActiveLogin(identifier: loginIdentifier)
            DispatchQueue.main.async {
                guard let self = self else { return }
                // Clear before any early return below so connection starts are
                // never left blocked by a refresh that has actually finished.
                self.isRefreshing = false
                if self.activeLoginIdentifier == loginIdentifier {
                    self.activeLoginIdentifier = nil
                }
                guard let delegate = self.delegate else { return }
                // Window closing (document gone): drop the response without
                // touching the torn-down UI. A user cancel of a *connection* can't
                // coincide with a refresh (Connect/Test are disabled while the
                // refresh runs), so it isn't treated as teardown here.
                if delegate.vaultRoleListWasTornDown() { return }

                self.progressIndicator?.stopAnimation(self)
                self.progressIndicator?.isHidden = true
                self.refreshButton?.isEnabled = true
                delegate.vaultRoleListSetConnectControlsEnabled(true)

                // Discard stale results: if any Vault context field changed while
                // the LIST was in flight, the response belongs to a different
                // request (possibly a different server) and must not be shown.
                if delegate.vaultRoleListCurrentHost() != host
                    || delegate.vaultRoleListCurrentPort() != port
                    || delegate.vaultRoleListCurrentOIDCMount() != oidcMount
                    || delegate.vaultRoleListCurrentMount() != mount {
                    return
                }

                if let roles = roles {
                    self.availableRoles = roles
                    self.reloadItems()
                    if roles.isEmpty {
                        NSAlert.createWarningAlert(title: NSLocalizedString("No Vault roles found", comment: "Vault roles refresh – empty"),
                                                   message: NSLocalizedString("No database roles were returned for this mount. Check the Vault mount path and that your token may list roles, or type the role manually.", comment: "Vault roles refresh – empty detail"))
                    }
                } else if !VaultAuthManager.isLoginCancellation(error) {
                    // A cancelled login (declined browser confirm, tab switch, or
                    // document teardown) is an expected abort, not a failure worth
                    // an alert — stay silent for those.
                    NSAlert.createWarningAlert(title: NSLocalizedString("Could not load Vault roles", comment: "Vault roles refresh – failure"),
                                               message: error?.localizedDescription ?? NSLocalizedString("Unknown error. You can still type the role manually.", comment: "Vault roles refresh – failure detail"))
                }
            }
        }
    }
}
