# frozen_string_literal: true

require "rake/testtask"

Rake::TestTask.new(:test) do |task|
  task.libs << File.expand_path("lib", __dir__)
  task.libs << File.expand_path("test", __dir__)
  task.pattern = File.expand_path("test/**/*_test.rb", __dir__)
  task.warning = true
end

task default: :test
